# Generated by Django 5.1.1 on 2024-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricalc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='member',
        ),
    ]
