# Generated by Django 5.1.1 on 2024-11-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutricalc', '0002_rename_user_user_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member',
            new_name='is_member',
        ),
    ]
