# Generated by Django 5.1.1 on 2024-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutricalc', '0003_rename_member_user_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_member',
            field=models.BooleanField(default=True),
        ),
    ]
